### PR TITLE
Rework of PR #14

### PR DESCRIPTION
**Pull request by lbschenkel**
Rework of #14

### CODE REVIEW

**Comment by lbschenkel** [comment]
@kathampy: Can you please test this out? I am particularly interested in the bridge autodiscovering your device (not finding it via explicit config); can you please test that and paste the log output here?

**Comment by kathampy** [comment]
I'll test it this weekend. Thanks.

**Comment by lbschenkel** [comment]
@kathampy: Had you have the chance to test if it works with your equipment, or not yet?

**Comment by kathampy** [comment]
The auto-discovery works with my RM4 Pro. However my registered commands no longer work via HTTP.

The commands are registered successfully from `config.ini`.
```
[commands]
diva/earcforcehdmi = 0000 006e 0000 0022 0156 00ab 0015 003f 0015 003f 0015 0015 0015 0015 0015 003f 0015 0015 0015 0015 0015 003f 0015 0015 0015 0015 0015 003f 0015 003f 0015 0015 0015 003f 0015 003f 0015 0015 0015 003f 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 003f 0015 003f 0015 003f 0015 1d0b
```
```
2022-03-22 12:51:54,359 INFO     Registering command: diva/earcforcehdmi
```

But the HTTP request fails.
```
POST http://localhost:8780/device/default HTTP/1.1

diva/earcforcehdmi
```
```
2022-03-22 12:52:06,544 WARNING  HTTP: POST /device/default HTTP/1.1 code 400, message Bad payload
```

If I send the hex code directly via HTTP instead of the command name, it works.

**Comment by lbschenkel** [comment]
> However my registered commands no longer work via HTTP.

This is strange, since nothing was changed in this PR regarding how commands are processed. Does it work for you when running the master branch?

**Comment by kathampy** [comment]
The master branch crashes with my device. I tried my old PR but get the same HTTP error with the command name. My config file is unchanged from before. Perhaps something else has changed in the environment. In any case the device support bug is fixed.

**Comment by lbschenkel** [comment]
Please double check that the command name you are passing really matches the configuration file.

I use this named command functionally every single day and I think I would have noticed if it stopped working. The 400 error you're getting is when the bridge cannot match the incoming data from the HTTP payload to a named command. I double checked your Pronto hex code and it is indeed valid (decoded to `NEC: {D=147,F=17}, beg=0, end=67`) so the problem must be a mismatch of names.

Try a simple test case like `test=...` to make sure the spaces in your file are actual spaces (`U+0020`) and not some other "space-like" character you might have entered by accident.

**Comment by lbschenkel** [comment]
> In any case the device support bug is fixed.

Great. I will merge this branch. The 400 error is unrelated to this PR.

**Comment by kathampy** [comment]
I tried a new barebones `config.ini` without any spaces, and used multiple HTTP clients. It just does not want to work with the command name. The hex codes without spaces works fine over HTTP.

I have Python 3.10.3. Is there another library used for config parsing which could have changed? Could you rebuild with the latest Python environment and test?

```
[commands]
test=0000006e00000022015600ab0015003f0015003f00150015001500150015003f00150015001500150015003f00150015001500150015003f0015003f001500150015003f0015003f001500150015003f0015001500150015001500150015003f001500150015001500150015001500150015003f0015003f0015003f001500150015003f0015003f0015003f00151d0b
```

**Comment by lbschenkel** [comment]
Hmm... I was inspecting the source code again and the `connect()` method might still be failing for you, and I forgot that it was used during transmission. I have pushed a new branch `test` with very quick & dirty `print()` statements (I will convert those to proper logging statements later when I have more time) to figure out what's going on. Please check out `test` and try again and tell me the output.

**Comment by kathampy** [comment]
I figured it out. Even though I terminated the `broadlink-bridge.exe` process, another `python.exe` was still running in the background which was using the default config.

There was no error in the newly launched `broadlink-bridge.exe` that there was a conflict, and the newly launched process was even printing the latest config output and HTTP commands. Somehow the loaded commands were mixed up in memory.

```
2022-03-22 16:12:09,145 INFO     Starting broadlink-bridge/0.1.8...
2022-03-22 16:12:09,145 INFO     Reading config file: config.ini
2022-03-22 16:12:09,147 INFO     Registering command: diva/earcforceauto
2022-03-22 16:12:09,147 INFO     Registering command: diva/earcforcehdmi
2022-03-22 16:12:09,148 INFO     Registering command: diva/hotplug
2022-03-22 16:12:09,148 INFO     Registering command: diva/inputsel0x
2022-03-22 16:12:09,148 INFO     Registering command: diva/inputsel1x
2022-03-22 16:12:09,149 INFO     Registering command: diva/inputsel2x
2022-03-22 16:12:09,150 INFO     Registering command: diva/inputsel3x
2022-03-22 16:12:09,150 INFO     Registering command: diva/reboot
2022-03-22 16:12:09,150 INFO     Discovery: searching for devices for 3 seconds...
trying hello
hello worked, trying auth
auth worked
dev = Wi-Fi Universal Remote (Broadlink RM4 pro 0x649b / 10.1.121.137:80 / 24:DF:A7:E4:66:76)
connected = True
dev = Wi-Fi Universal Remote (Broadlink RM4 pro 0x649b / 10.1.121.137:80 / 24:DF:A7:E4:66:76)
connected = True
2022-03-22 16:12:12,214 INFO     Connected: Wi-Fi Universal Remote (Broadlink RM4 pro 0x649b / 10.1.121.137:80 / 24:DF:A7:E4:66:76)
connect() worked
already connected
2022-03-22 16:12:12,219 INFO     Device: 24-DF-A7-E4-66-76@10.1.121.137 has alias 10.1.121.137
2022-03-22 16:12:12,235 INFO     HTTP server started on port 8780
2022-03-22 16:12:12,235 INFO     LIRC server disabled
2022-03-22 16:12:12,236 INFO     MQTT client disabled
attempting to transmit = b'diva/earcforcehdmi'
transmitting code = diva/earcforcehdmi
real code = diva/earcforcehdmi
already connected
sending = bytearray(b'&\x00H\x00\x00\x01*\x95\x126\x126\x12\x12\x12\x12\x126\x12\x12\x12\x12\x126\x12\x12\x12\x12\x126\x126\x12\x12\x126\x126\x12\x12\x126\x12\x12\x12\x12\x12\x12\x126\x12\x12\x12\x12\x12\x12\x12\x12\x126\x126\x126\x12\x12\x126\x126\x126\x12\x00\x19N\r\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
sent
success, returning 204
```

**Comment by kathampy** [comment]
`Ctrl + C`, `Ctrl + Z`, or `Ctrl + Pause / Break` don't work in this application and I have to terminate the process manually. Can this be supported? A clean shutdown would also prevent situations like above.

**Comment by lbschenkel** [comment]
I will look into that when I have the chance, but please create a separate issue for tracking purposes.

**Pull request merged**
